# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov 13 15:46:11 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 320)
        MainWindow.setMinimumSize(QtCore.QSize(500, 320))
        MainWindow.setMaximumSize(QtCore.QSize(700, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/Bus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayoutSettings = QtGui.QGridLayout()
        self.gridLayoutSettings.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayoutSettings.setObjectName(_fromUtf8("gridLayoutSettings"))
        self.lblPIDModel = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPIDModel.sizePolicy().hasHeightForWidth())
        self.lblPIDModel.setSizePolicy(sizePolicy)
        self.lblPIDModel.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPIDModel.setFont(font)
        self.lblPIDModel.setFrameShape(QtGui.QFrame.Box)
        self.lblPIDModel.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblPIDModel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPIDModel.setObjectName(_fromUtf8("lblPIDModel"))
        self.gridLayoutSettings.addWidget(self.lblPIDModel, 1, 0, 1, 1)
        self.lblProccess = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProccess.sizePolicy().hasHeightForWidth())
        self.lblProccess.setSizePolicy(sizePolicy)
        self.lblProccess.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProccess.setFont(font)
        self.lblProccess.setFrameShape(QtGui.QFrame.Box)
        self.lblProccess.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblProccess.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProccess.setObjectName(_fromUtf8("lblProccess"))
        self.gridLayoutSettings.addWidget(self.lblProccess, 0, 2, 1, 1)
        self.lblPID = QtGui.QLabel(self.centralWidget)
        self.lblPID.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPID.setFont(font)
        self.lblPID.setFrameShape(QtGui.QFrame.Box)
        self.lblPID.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblPID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPID.setObjectName(_fromUtf8("lblPID"))
        self.gridLayoutSettings.addWidget(self.lblPID, 1, 2, 1, 1)
        self.lblProccessModel = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProccessModel.sizePolicy().hasHeightForWidth())
        self.lblProccessModel.setSizePolicy(sizePolicy)
        self.lblProccessModel.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProccessModel.setFont(font)
        self.lblProccessModel.setFrameShape(QtGui.QFrame.Box)
        self.lblProccessModel.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblProccessModel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProccessModel.setObjectName(_fromUtf8("lblProccessModel"))
        self.gridLayoutSettings.addWidget(self.lblProccessModel, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutSettings)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuModels = QtGui.QMenu(self.menuBar)
        self.menuModels.setObjectName(_fromUtf8("menuModels"))
        self.menuPID = QtGui.QMenu(self.menuBar)
        self.menuPID.setObjectName(_fromUtf8("menuPID"))
        self.menuClosed_Loop = QtGui.QMenu(self.menuBar)
        self.menuClosed_Loop.setObjectName(_fromUtf8("menuClosed_Loop"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/close16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/info16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/options-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon3)
        self.actionSettings.setIconVisibleInMenu(True)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionProccessTF = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/text_superscript-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProccessTF.setIcon(icon4)
        self.actionProccessTF.setObjectName(_fromUtf8("actionProccessTF"))
        self.actionPID_Controller = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/gcp-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPID_Controller.setIcon(icon5)
        self.actionPID_Controller.setObjectName(_fromUtf8("actionPID_Controller"))
        self.actionReset_Models = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/refresh-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionReset_Models.setIcon(icon6)
        self.actionReset_Models.setObjectName(_fromUtf8("actionReset_Models"))
        self.actionTime_Domain_Graph = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/chart_curve-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTime_Domain_Graph.setIcon(icon7)
        self.actionTime_Domain_Graph.setObjectName(_fromUtf8("actionTime_Domain_Graph"))
        self.actionFreq_Domain_Graph = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/linechart-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFreq_Domain_Graph.setIcon(icon8)
        self.actionFreq_Domain_Graph.setObjectName(_fromUtf8("actionFreq_Domain_Graph"))
        self.actionCLTime_Domain_Graph = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/diagramm-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCLTime_Domain_Graph.setIcon(icon9)
        self.actionCLTime_Domain_Graph.setObjectName(_fromUtf8("actionCLTime_Domain_Graph"))
        self.actionCLFreq_Domain_Graph = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/vector-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCLFreq_Domain_Graph.setIcon(icon10)
        self.actionCLFreq_Domain_Graph.setObjectName(_fromUtf8("actionCLFreq_Domain_Graph"))
        self.actionCLNyquist_Graph = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/centroid-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCLNyquist_Graph.setIcon(icon11)
        self.actionCLNyquist_Graph.setObjectName(_fromUtf8("actionCLNyquist_Graph"))
        self.menuFile.addAction(self.actionReset_Models)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuModels.addAction(self.actionProccessTF)
        self.menuModels.addSeparator()
        self.menuModels.addAction(self.actionTime_Domain_Graph)
        self.menuModels.addAction(self.actionFreq_Domain_Graph)
        self.menuPID.addAction(self.actionPID_Controller)
        self.menuPID.addSeparator()
        self.menuClosed_Loop.addAction(self.actionCLTime_Domain_Graph)
        self.menuClosed_Loop.addAction(self.actionCLFreq_Domain_Graph)
        self.menuClosed_Loop.addAction(self.actionCLNyquist_Graph)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuModels.menuAction())
        self.menuBar.addAction(self.menuPID.menuAction())
        self.menuBar.addAction(self.menuClosed_Loop.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PID Tune", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPIDModel.setText(QtGui.QApplication.translate("MainWindow", "PID", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProccess.setText(QtGui.QApplication.translate("MainWindow", "None\n"
"Delay : 0.0s, Pade : 1", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPID.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProccessModel.setText(QtGui.QApplication.translate("MainWindow", "Proccess", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuModels.setTitle(QtGui.QApplication.translate("MainWindow", "Proccess", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPID.setTitle(QtGui.QApplication.translate("MainWindow", "PID", None, QtGui.QApplication.UnicodeUTF8))
        self.menuClosed_Loop.setTitle(QtGui.QApplication.translate("MainWindow", "Closed Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProccessTF.setText(QtGui.QApplication.translate("MainWindow", "Transfer Function", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProccessTF.setIconText(QtGui.QApplication.translate("MainWindow", "Transfer Function", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProccessTF.setToolTip(QtGui.QApplication.translate("MainWindow", "Proccess Transfer Function", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPID_Controller.setText(QtGui.QApplication.translate("MainWindow", "PID Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Models.setText(QtGui.QApplication.translate("MainWindow", "Reset Models", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime_Domain_Graph.setText(QtGui.QApplication.translate("MainWindow", "Time Domain Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime_Domain_Graph.setToolTip(QtGui.QApplication.translate("MainWindow", "Proccess Time Domain Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFreq_Domain_Graph.setText(QtGui.QApplication.translate("MainWindow", "Freq Domain Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFreq_Domain_Graph.setToolTip(QtGui.QApplication.translate("MainWindow", "Proccess Freq Domain Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCLTime_Domain_Graph.setText(QtGui.QApplication.translate("MainWindow", "Time Domain Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCLTime_Domain_Graph.setToolTip(QtGui.QApplication.translate("MainWindow", "Closed Loop Time Domain Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCLFreq_Domain_Graph.setText(QtGui.QApplication.translate("MainWindow", "Freq Domain Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCLFreq_Domain_Graph.setToolTip(QtGui.QApplication.translate("MainWindow", "Closed Loop Freq Domain Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCLNyquist_Graph.setText(QtGui.QApplication.translate("MainWindow", "Nyquist Graph", None, QtGui.QApplication.UnicodeUTF8))

import pyPIDTune_rc
