# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pid_ctrl_model.ui'
#
# Created: Tue Nov 19 09:33:43 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PIDCtrlModel(object):
    def setupUi(self, PIDCtrlModel):
        PIDCtrlModel.setObjectName(_fromUtf8("PIDCtrlModel"))
        PIDCtrlModel.setWindowModality(QtCore.Qt.NonModal)
        PIDCtrlModel.resize(290, 320)
        PIDCtrlModel.setMinimumSize(QtCore.QSize(290, 320))
        PIDCtrlModel.setMaximumSize(QtCore.QSize(290, 320))
        PIDCtrlModel.setModal(True)
        self.gridLayoutWidget = QtGui.QWidget(PIDCtrlModel)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 152))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblPIDType = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPIDType.setFont(font)
        self.lblPIDType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPIDType.setObjectName(_fromUtf8("lblPIDType"))
        self.gridLayout.addWidget(self.lblPIDType, 0, 0, 1, 1)
        self.cmbPIDType = QtGui.QComboBox(self.gridLayoutWidget)
        self.cmbPIDType.setObjectName(_fromUtf8("cmbPIDType"))
        self.cmbPIDType.addItem(_fromUtf8(""))
        self.cmbPIDType.addItem(_fromUtf8(""))
        self.cmbPIDType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPIDType, 0, 1, 1, 1)
        self.lblKc = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblKc.setFont(font)
        self.lblKc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblKc.setObjectName(_fromUtf8("lblKc"))
        self.gridLayout.addWidget(self.lblKc, 2, 0, 1, 1)
        self.leKc = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leKc.setObjectName(_fromUtf8("leKc"))
        self.gridLayout.addWidget(self.leKc, 2, 1, 1, 1)
        self.chbTi = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chbTi.setFont(font)
        self.chbTi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbTi.setObjectName(_fromUtf8("chbTi"))
        self.gridLayout.addWidget(self.chbTi, 3, 0, 1, 1)
        self.leTi = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leTi.setObjectName(_fromUtf8("leTi"))
        self.gridLayout.addWidget(self.leTi, 3, 1, 1, 1)
        self.chbTd = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chbTd.setFont(font)
        self.chbTd.setObjectName(_fromUtf8("chbTd"))
        self.gridLayout.addWidget(self.chbTd, 4, 0, 1, 1)
        self.leTd = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leTd.setObjectName(_fromUtf8("leTd"))
        self.gridLayout.addWidget(self.leTd, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.lblTuneMethod = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTuneMethod.setFont(font)
        self.lblTuneMethod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTuneMethod.setObjectName(_fromUtf8("lblTuneMethod"))
        self.gridLayout.addWidget(self.lblTuneMethod, 1, 0, 1, 1)
        self.cmbTuneMethod = QtGui.QComboBox(self.gridLayoutWidget)
        self.cmbTuneMethod.setObjectName(_fromUtf8("cmbTuneMethod"))
        self.gridLayout.addWidget(self.cmbTuneMethod, 1, 1, 1, 1)
        self.cmbPIDConfig = QtGui.QComboBox(self.gridLayoutWidget)
        self.cmbPIDConfig.setObjectName(_fromUtf8("cmbPIDConfig"))
        self.gridLayout.addWidget(self.cmbPIDConfig, 1, 2, 1, 1)
        self.lblTf = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTf.setFont(font)
        self.lblTf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTf.setObjectName(_fromUtf8("lblTf"))
        self.gridLayout.addWidget(self.lblTf, 5, 0, 1, 1)
        self.leTf = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leTf.setObjectName(_fromUtf8("leTf"))
        self.gridLayout.addWidget(self.leTf, 5, 1, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(PIDCtrlModel)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 271, 128))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblTF = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTF.setFont(font)
        self.lblTF.setFrameShape(QtGui.QFrame.Box)
        self.lblTF.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTF.setText(_fromUtf8(""))
        self.lblTF.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTF.setObjectName(_fromUtf8("lblTF"))
        self.verticalLayout.addWidget(self.lblTF)
        self.buttonBox = QtGui.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PIDCtrlModel)
        self.cmbPIDType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PIDCtrlModel)

    def retranslateUi(self, PIDCtrlModel):
        PIDCtrlModel.setWindowTitle(QtGui.QApplication.translate("PIDCtrlModel", "PID Model", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPIDType.setText(QtGui.QApplication.translate("PIDCtrlModel", "PID Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPIDType.setItemText(0, QtGui.QApplication.translate("PIDCtrlModel", "Standard PID", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPIDType.setItemText(1, QtGui.QApplication.translate("PIDCtrlModel", "Parallel PID", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPIDType.setItemText(2, QtGui.QApplication.translate("PIDCtrlModel", "Predefined PIDs", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKc.setText(QtGui.QApplication.translate("PIDCtrlModel", "Kc", None, QtGui.QApplication.UnicodeUTF8))
        self.chbTi.setText(QtGui.QApplication.translate("PIDCtrlModel", "Ti", None, QtGui.QApplication.UnicodeUTF8))
        self.chbTd.setText(QtGui.QApplication.translate("PIDCtrlModel", "Td", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTuneMethod.setText(QtGui.QApplication.translate("PIDCtrlModel", "Tune Method", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTf.setText(QtGui.QApplication.translate("PIDCtrlModel", "Tf", None, QtGui.QApplication.UnicodeUTF8))

